# Generated by Django 4.2.1 on 2023-05-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_tag_user_role_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="expired_date",
            field=models.DateTimeField(
                null=True, verbose_name="the date by which the task must be completed"
            ),
        ),
    ]
