# Generated by Django 4.2.1 on 2023-05-12 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_task_author_alter_task_performer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author of the task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="performer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="performer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="performer of the task",
            ),
        ),
    ]
