name: Docker and Tests CI

on: [pull_request, push] 

jobs:
  build:

    runs-on: ubuntu-latest

  
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build -t task-manager .

    - name: Run Tests
      run: |
        docker-compose run --rm api poetry run pytest
    
